# Generated by Django 4.0 on 2021-12-16 22:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('price', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('pending', 'Pending'), ('reversed', 'Reversed')], max_length=20)),
                ('approved', models.BooleanField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='pststats.company')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(check=models.Q(('name', ''), _negated=True), name='company-name-non-empty'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(check=models.Q(('slug', ''), _negated=True), name='company-slug-non-empty'),
        ),
    ]
